name: firebase_user_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none
environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_storage:
  dio: ^5.8.0

  user_api:
    path: ../user_api

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
